#pragma once
#include <stdint.h>

extern const int __ARCHX86_KERNEL_PHYSICAL_ADDRESS_BEGIN__;
extern const int __ARCHX86_KERNEL_PHYSICAL_ADDRESS_END__;

#define ARCHX86_KERNEL_PHYSICAL_ADDRESS_BEGIN  ((uintptr_t)&__ARCHX86_KERNEL_PHYSICAL_ADDRESS_BEGIN__)
#define ARCHX86_KERNEL_PHYSICAL_ADDRESS_END    ((uintptr_t)&__ARCHX86_KERNEL_PHYSICAL_ADDRESS_END__)

extern const int __ARCHX86_KERNEL_TEXT_BEGIN__;
extern const int __ARCHX86_KERNEL_TEXT_END__;

#define ARCHX86_ARCH_KERNEL_TEXT_BEGIN  ((uintptr_t)&__ARCHX86_KERNEL_TEXT_BEGIN__)
#define ARCHX86_ARCH_KERNEL_TEXT_END    ((uintptr_t)&__ARCHX86_KERNEL_TEXT_END__)

extern const int __ARCHX86_KERNEL_RO_AFTER_EARLY_INIT_BEGIN__;
extern const int __ARCHX86_KERNEL_RO_AFTER_EARLY_INIT_END__;

#define ARCHX86_KERNEL_RO_AFTER_EARLY_INIT_BEGIN  ((uintptr_t)&__ARCHX86_KERNEL_RO_AFTER_EARLY_INIT_BEGIN__)
#define ARCHX86_KERNEL_RO_AFTER_EARLY_INIT_END    ((uintptr_t)&__ARCHX86_KERNEL_RO_AFTER_EARLY_INIT_END__)

extern const int __ARCH_KERNEL_VIRTUAL_ADDRESS_BEGIN__;
extern const int __ARCH_KERNEL_VIRTUAL_ADDRESS_END__;

#define ARCH_KERNEL_VIRTUAL_ADDRESS_BEGIN  ((uintptr_t)&__ARCH_KERNEL_VIRTUAL_ADDRESS_BEGIN__)
#define ARCH_KERNEL_VIRTUAL_ADDRESS_END    ((uintptr_t)&__ARCH_KERNEL_VIRTUAL_ADDRESS_END__)
