.global archx86_isr_exception0entry,  archx86_isr_exception1entry,  archx86_isr_exception2entry,  archx86_isr_exception3entry
.global archx86_isr_exception4entry,  archx86_isr_exception5entry,  archx86_isr_exception6entry,  archx86_isr_exception7entry
.global archx86_isr_exception8entry,  archx86_isr_exception9entry,  archx86_isr_exception10entry, archx86_isr_exception11entry
.global archx86_isr_exception12entry, archx86_isr_exception13entry, archx86_isr_exception14entry, archx86_isr_exception15entry
.global archx86_isr_exception16entry, archx86_isr_exception17entry, archx86_isr_exception18entry, archx86_isr_exception19entry
.global archx86_isr_exception20entry, archx86_isr_exception21entry, archx86_isr_exception22entry, archx86_isr_exception23entry
.global archx86_isr_exception24entry, archx86_isr_exception25entry, archx86_isr_exception26entry, archx86_isr_exception27entry
.global archx86_isr_exception28entry, archx86_isr_exception29entry, archx86_isr_exception30entry, archx86_isr_exception31entry

.global archx86_isr_interrupt32entry,  archx86_isr_interrupt33entry,  archx86_isr_interrupt34entry,  archx86_isr_interrupt35entry
.global archx86_isr_interrupt36entry,  archx86_isr_interrupt37entry,  archx86_isr_interrupt38entry,  archx86_isr_interrupt39entry
.global archx86_isr_interrupt40entry,  archx86_isr_interrupt41entry,  archx86_isr_interrupt42entry,  archx86_isr_interrupt43entry
.global archx86_isr_interrupt44entry,  archx86_isr_interrupt45entry,  archx86_isr_interrupt46entry,  archx86_isr_interrupt47entry
.global archx86_isr_interrupt48entry,  archx86_isr_interrupt49entry,  archx86_isr_interrupt50entry,  archx86_isr_interrupt51entry
.global archx86_isr_interrupt52entry,  archx86_isr_interrupt53entry,  archx86_isr_interrupt54entry,  archx86_isr_interrupt55entry
.global archx86_isr_interrupt56entry,  archx86_isr_interrupt57entry,  archx86_isr_interrupt58entry,  archx86_isr_interrupt59entry
.global archx86_isr_interrupt60entry,  archx86_isr_interrupt61entry,  archx86_isr_interrupt62entry,  archx86_isr_interrupt63entry
.global archx86_isr_interrupt64entry,  archx86_isr_interrupt65entry,  archx86_isr_interrupt66entry,  archx86_isr_interrupt67entry
.global archx86_isr_interrupt68entry,  archx86_isr_interrupt69entry,  archx86_isr_interrupt70entry,  archx86_isr_interrupt71entry
.global archx86_isr_interrupt72entry,  archx86_isr_interrupt73entry,  archx86_isr_interrupt74entry,  archx86_isr_interrupt75entry
.global archx86_isr_interrupt76entry,  archx86_isr_interrupt77entry,  archx86_isr_interrupt78entry,  archx86_isr_interrupt79entry
.global archx86_isr_interrupt80entry,  archx86_isr_interrupt81entry,  archx86_isr_interrupt82entry,  archx86_isr_interrupt83entry
.global archx86_isr_interrupt84entry,  archx86_isr_interrupt85entry,  archx86_isr_interrupt86entry,  archx86_isr_interrupt87entry
.global archx86_isr_interrupt88entry,  archx86_isr_interrupt89entry,  archx86_isr_interrupt90entry,  archx86_isr_interrupt91entry
.global archx86_isr_interrupt92entry,  archx86_isr_interrupt93entry,  archx86_isr_interrupt94entry,  archx86_isr_interrupt95entry
.global archx86_isr_interrupt96entry,  archx86_isr_interrupt97entry,  archx86_isr_interrupt98entry,  archx86_isr_interrupt99entry
.global archx86_isr_interrupt100entry, archx86_isr_interrupt101entry, archx86_isr_interrupt102entry, archx86_isr_interrupt103entry
.global archx86_isr_interrupt104entry, archx86_isr_interrupt105entry, archx86_isr_interrupt106entry, archx86_isr_interrupt107entry
.global archx86_isr_interrupt108entry, archx86_isr_interrupt109entry, archx86_isr_interrupt110entry, archx86_isr_interrupt111entry
.global archx86_isr_interrupt112entry, archx86_isr_interrupt113entry, archx86_isr_interrupt114entry, archx86_isr_interrupt115entry
.global archx86_isr_interrupt116entry, archx86_isr_interrupt117entry, archx86_isr_interrupt118entry, archx86_isr_interrupt119entry
.global archx86_isr_interrupt120entry, archx86_isr_interrupt121entry, archx86_isr_interrupt122entry, archx86_isr_interrupt123entry
.global archx86_isr_interrupt124entry, archx86_isr_interrupt125entry, archx86_isr_interrupt126entry, archx86_isr_interrupt127entry
.global archx86_isr_interrupt128entry, archx86_isr_interrupt129entry, archx86_isr_interrupt130entry, archx86_isr_interrupt131entry
.global archx86_isr_interrupt132entry, archx86_isr_interrupt133entry, archx86_isr_interrupt134entry, archx86_isr_interrupt135entry
.global archx86_isr_interrupt136entry, archx86_isr_interrupt137entry, archx86_isr_interrupt138entry, archx86_isr_interrupt139entry
.global archx86_isr_interrupt140entry, archx86_isr_interrupt141entry, archx86_isr_interrupt142entry, archx86_isr_interrupt143entry
.global archx86_isr_interrupt144entry, archx86_isr_interrupt145entry, archx86_isr_interrupt146entry, archx86_isr_interrupt147entry
.global archx86_isr_interrupt148entry, archx86_isr_interrupt149entry, archx86_isr_interrupt150entry, archx86_isr_interrupt151entry
.global archx86_isr_interrupt152entry, archx86_isr_interrupt153entry, archx86_isr_interrupt154entry, archx86_isr_interrupt155entry
.global archx86_isr_interrupt156entry, archx86_isr_interrupt157entry, archx86_isr_interrupt158entry, archx86_isr_interrupt159entry
.global archx86_isr_interrupt160entry, archx86_isr_interrupt161entry, archx86_isr_interrupt162entry, archx86_isr_interrupt163entry
.global archx86_isr_interrupt164entry, archx86_isr_interrupt165entry, archx86_isr_interrupt166entry, archx86_isr_interrupt167entry
.global archx86_isr_interrupt168entry, archx86_isr_interrupt169entry, archx86_isr_interrupt170entry, archx86_isr_interrupt171entry
.global archx86_isr_interrupt172entry, archx86_isr_interrupt173entry, archx86_isr_interrupt174entry, archx86_isr_interrupt175entry
.global archx86_isr_interrupt176entry, archx86_isr_interrupt177entry, archx86_isr_interrupt178entry, archx86_isr_interrupt179entry
.global archx86_isr_interrupt180entry, archx86_isr_interrupt181entry, archx86_isr_interrupt182entry, archx86_isr_interrupt183entry
.global archx86_isr_interrupt184entry, archx86_isr_interrupt185entry, archx86_isr_interrupt186entry, archx86_isr_interrupt187entry
.global archx86_isr_interrupt188entry, archx86_isr_interrupt189entry, archx86_isr_interrupt190entry, archx86_isr_interrupt191entry
.global archx86_isr_interrupt192entry, archx86_isr_interrupt193entry, archx86_isr_interrupt194entry, archx86_isr_interrupt195entry
.global archx86_isr_interrupt196entry, archx86_isr_interrupt197entry, archx86_isr_interrupt198entry, archx86_isr_interrupt199entry
.global archx86_isr_interrupt200entry, archx86_isr_interrupt201entry, archx86_isr_interrupt202entry, archx86_isr_interrupt203entry
.global archx86_isr_interrupt204entry, archx86_isr_interrupt205entry, archx86_isr_interrupt206entry, archx86_isr_interrupt207entry
.global archx86_isr_interrupt208entry, archx86_isr_interrupt209entry, archx86_isr_interrupt210entry, archx86_isr_interrupt211entry
.global archx86_isr_interrupt212entry, archx86_isr_interrupt213entry, archx86_isr_interrupt214entry, archx86_isr_interrupt215entry
.global archx86_isr_interrupt216entry, archx86_isr_interrupt217entry, archx86_isr_interrupt218entry, archx86_isr_interrupt219entry
.global archx86_isr_interrupt220entry, archx86_isr_interrupt221entry, archx86_isr_interrupt222entry, archx86_isr_interrupt223entry
.global archx86_isr_interrupt224entry, archx86_isr_interrupt225entry, archx86_isr_interrupt226entry, archx86_isr_interrupt227entry
.global archx86_isr_interrupt228entry, archx86_isr_interrupt229entry, archx86_isr_interrupt230entry, archx86_isr_interrupt231entry
.global archx86_isr_interrupt232entry, archx86_isr_interrupt233entry, archx86_isr_interrupt234entry, archx86_isr_interrupt235entry
.global archx86_isr_interrupt236entry, archx86_isr_interrupt237entry, archx86_isr_interrupt238entry, archx86_isr_interrupt239entry
.global archx86_isr_interrupt240entry, archx86_isr_interrupt241entry, archx86_isr_interrupt242entry, archx86_isr_interrupt243entry
.global archx86_isr_interrupt244entry, archx86_isr_interrupt245entry, archx86_isr_interrupt246entry, archx86_isr_interrupt247entry
.global archx86_isr_interrupt248entry, archx86_isr_interrupt249entry, archx86_isr_interrupt250entry, archx86_isr_interrupt251entry
.global archx86_isr_interrupt252entry, archx86_isr_interrupt253entry, archx86_isr_interrupt254entry, archx86_isr_interrupt255entry

.macro isr_exc_header
    cli
.endm

.macro push_fake_code
    push $0
.endm

.macro save_regs
    pusha
    mov %ds, %eax
    push %eax
    mov %es, %eax
    push %eax
    mov %fs, %eax
    push %eax 
    mov %gs, %eax
    push %eax 
.endm

.macro restore_regs
    add $8, %esp /* Skip FS and GS */
    pop %eax
    mov %eax, %es
    pop %eax
    mov %eax, %ds
    popa
.endm

.macro isr_footer
    add $4, %esp
    iret
.endm

.macro call_handler n
    mov %esp, %ebx
    /* Align the stack */
    and $~0x0F, %esp
    /* Call the handler */
    push %ebx /* Arg 1 */
    push $\n  /* Arg 0 */
    call trapmanager_trap
    /* Restore ESP */
    mov %ebx, %esp
.endm

.macro isr_excentry n
    isr_exc_header
    save_regs
    call_handler \n
    restore_regs
    isr_footer 
.endm

.macro isr_excentry_nocode n
    isr_exc_header
    push_fake_code
    save_regs
    call_handler \n
    restore_regs
    isr_footer 
.endm

.macro isr_intentry n
    push_fake_code
    save_regs
    call_handler \n
    restore_regs
    isr_footer 
.endm

archx86_isr_exception0entry:  isr_excentry_nocode 0
archx86_isr_exception1entry:  isr_excentry_nocode 1
archx86_isr_exception2entry:  isr_excentry_nocode 2
archx86_isr_exception3entry:  isr_excentry_nocode 3
archx86_isr_exception4entry:  isr_excentry_nocode 4
archx86_isr_exception5entry:  isr_excentry_nocode 5
archx86_isr_exception6entry:  isr_excentry_nocode 6
/* archx86_isr_exception7entry:  isr_excentry_nocode 7 */
archx86_isr_exception7entry:  jmp archx86_isr_exception7entry
archx86_isr_exception8entry:  isr_excentry        8
archx86_isr_exception9entry:  isr_excentry_nocode 9
archx86_isr_exception10entry: isr_excentry        10
archx86_isr_exception11entry: isr_excentry        11
archx86_isr_exception12entry: isr_excentry        12
archx86_isr_exception13entry: isr_excentry        13
archx86_isr_exception14entry: isr_excentry        14
archx86_isr_exception15entry: isr_excentry_nocode 15
archx86_isr_exception16entry: isr_excentry_nocode 16
archx86_isr_exception17entry: isr_excentry        17
archx86_isr_exception18entry: isr_excentry_nocode 18
archx86_isr_exception19entry: isr_excentry_nocode 19
archx86_isr_exception20entry: isr_excentry_nocode 20
archx86_isr_exception21entry: isr_excentry        21
archx86_isr_exception22entry: isr_excentry_nocode 22
archx86_isr_exception23entry: isr_excentry_nocode 23
archx86_isr_exception24entry: isr_excentry_nocode 24
archx86_isr_exception25entry: isr_excentry_nocode 25
archx86_isr_exception26entry: isr_excentry_nocode 26
archx86_isr_exception27entry: isr_excentry_nocode 27
archx86_isr_exception28entry: isr_excentry_nocode 28
archx86_isr_exception29entry: isr_excentry        29
archx86_isr_exception30entry: isr_excentry        30
archx86_isr_exception31entry: isr_excentry_nocode 31

archx86_isr_interrupt32entry:  isr_intentry 32
archx86_isr_interrupt33entry:  isr_intentry 33
archx86_isr_interrupt34entry:  isr_intentry 34
archx86_isr_interrupt35entry:  isr_intentry 35
archx86_isr_interrupt36entry:  isr_intentry 36
archx86_isr_interrupt37entry:  isr_intentry 37
archx86_isr_interrupt38entry:  isr_intentry 38
archx86_isr_interrupt39entry:  isr_intentry 39
archx86_isr_interrupt40entry:  isr_intentry 40
archx86_isr_interrupt41entry:  isr_intentry 41
archx86_isr_interrupt42entry:  isr_intentry 42
archx86_isr_interrupt43entry:  isr_intentry 43
archx86_isr_interrupt44entry:  isr_intentry 44
archx86_isr_interrupt45entry:  isr_intentry 45
archx86_isr_interrupt46entry:  isr_intentry 46
archx86_isr_interrupt47entry:  isr_intentry 47
archx86_isr_interrupt48entry:  isr_intentry 48
archx86_isr_interrupt49entry:  isr_intentry 49
archx86_isr_interrupt50entry:  isr_intentry 50
archx86_isr_interrupt51entry:  isr_intentry 51
archx86_isr_interrupt52entry:  isr_intentry 52
archx86_isr_interrupt53entry:  isr_intentry 53
archx86_isr_interrupt54entry:  isr_intentry 54
archx86_isr_interrupt55entry:  isr_intentry 55
archx86_isr_interrupt56entry:  isr_intentry 56
archx86_isr_interrupt57entry:  isr_intentry 57
archx86_isr_interrupt58entry:  isr_intentry 58
archx86_isr_interrupt59entry:  isr_intentry 59
archx86_isr_interrupt60entry:  isr_intentry 60
archx86_isr_interrupt61entry:  isr_intentry 61
archx86_isr_interrupt62entry:  isr_intentry 62
archx86_isr_interrupt63entry:  isr_intentry 63
archx86_isr_interrupt64entry:  isr_intentry 64
archx86_isr_interrupt65entry:  isr_intentry 65
archx86_isr_interrupt66entry:  isr_intentry 66
archx86_isr_interrupt67entry:  isr_intentry 67
archx86_isr_interrupt68entry:  isr_intentry 68
archx86_isr_interrupt69entry:  isr_intentry 69
archx86_isr_interrupt70entry:  isr_intentry 70
archx86_isr_interrupt71entry:  isr_intentry 71
archx86_isr_interrupt72entry:  isr_intentry 72
archx86_isr_interrupt73entry:  isr_intentry 73
archx86_isr_interrupt74entry:  isr_intentry 74
archx86_isr_interrupt75entry:  isr_intentry 75
archx86_isr_interrupt76entry:  isr_intentry 76
archx86_isr_interrupt77entry:  isr_intentry 77
archx86_isr_interrupt78entry:  isr_intentry 78
archx86_isr_interrupt79entry:  isr_intentry 79
archx86_isr_interrupt80entry:  isr_intentry 80
archx86_isr_interrupt81entry:  isr_intentry 81
archx86_isr_interrupt82entry:  isr_intentry 82
archx86_isr_interrupt83entry:  isr_intentry 83
archx86_isr_interrupt84entry:  isr_intentry 84
archx86_isr_interrupt85entry:  isr_intentry 85
archx86_isr_interrupt86entry:  isr_intentry 86
archx86_isr_interrupt87entry:  isr_intentry 87
archx86_isr_interrupt88entry:  isr_intentry 88
archx86_isr_interrupt89entry:  isr_intentry 89
archx86_isr_interrupt90entry:  isr_intentry 90
archx86_isr_interrupt91entry:  isr_intentry 91
archx86_isr_interrupt92entry:  isr_intentry 92
archx86_isr_interrupt93entry:  isr_intentry 93
archx86_isr_interrupt94entry:  isr_intentry 94
archx86_isr_interrupt95entry:  isr_intentry 95
archx86_isr_interrupt96entry:  isr_intentry 96
archx86_isr_interrupt97entry:  isr_intentry 97
archx86_isr_interrupt98entry:  isr_intentry 98
archx86_isr_interrupt99entry:  isr_intentry 99
archx86_isr_interrupt100entry: isr_intentry 100
archx86_isr_interrupt101entry: isr_intentry 101
archx86_isr_interrupt102entry: isr_intentry 102
archx86_isr_interrupt103entry: isr_intentry 103
archx86_isr_interrupt104entry: isr_intentry 104
archx86_isr_interrupt105entry: isr_intentry 105
archx86_isr_interrupt106entry: isr_intentry 106
archx86_isr_interrupt107entry: isr_intentry 107
archx86_isr_interrupt108entry: isr_intentry 108
archx86_isr_interrupt109entry: isr_intentry 109
archx86_isr_interrupt110entry: isr_intentry 110
archx86_isr_interrupt111entry: isr_intentry 111
archx86_isr_interrupt112entry: isr_intentry 112
archx86_isr_interrupt113entry: isr_intentry 113
archx86_isr_interrupt114entry: isr_intentry 114
archx86_isr_interrupt115entry: isr_intentry 115
archx86_isr_interrupt116entry: isr_intentry 116
archx86_isr_interrupt117entry: isr_intentry 117
archx86_isr_interrupt118entry: isr_intentry 118
archx86_isr_interrupt119entry: isr_intentry 119
archx86_isr_interrupt120entry: isr_intentry 120
archx86_isr_interrupt121entry: isr_intentry 121
archx86_isr_interrupt122entry: isr_intentry 122
archx86_isr_interrupt123entry: isr_intentry 123
archx86_isr_interrupt124entry: isr_intentry 124
archx86_isr_interrupt125entry: isr_intentry 125
archx86_isr_interrupt126entry: isr_intentry 126
archx86_isr_interrupt127entry: isr_intentry 127
archx86_isr_interrupt128entry: isr_intentry 128
archx86_isr_interrupt129entry: isr_intentry 129
archx86_isr_interrupt130entry: isr_intentry 130
archx86_isr_interrupt131entry: isr_intentry 131
archx86_isr_interrupt132entry: isr_intentry 132
archx86_isr_interrupt133entry: isr_intentry 133
archx86_isr_interrupt134entry: isr_intentry 134
archx86_isr_interrupt135entry: isr_intentry 135
archx86_isr_interrupt136entry: isr_intentry 136
archx86_isr_interrupt137entry: isr_intentry 137
archx86_isr_interrupt138entry: isr_intentry 138
archx86_isr_interrupt139entry: isr_intentry 139
archx86_isr_interrupt140entry: isr_intentry 140
archx86_isr_interrupt141entry: isr_intentry 141
archx86_isr_interrupt142entry: isr_intentry 142
archx86_isr_interrupt143entry: isr_intentry 143
archx86_isr_interrupt144entry: isr_intentry 144
archx86_isr_interrupt145entry: isr_intentry 145
archx86_isr_interrupt146entry: isr_intentry 146
archx86_isr_interrupt147entry: isr_intentry 147
archx86_isr_interrupt148entry: isr_intentry 148
archx86_isr_interrupt149entry: isr_intentry 149
archx86_isr_interrupt150entry: isr_intentry 150
archx86_isr_interrupt151entry: isr_intentry 151
archx86_isr_interrupt152entry: isr_intentry 152
archx86_isr_interrupt153entry: isr_intentry 153
archx86_isr_interrupt154entry: isr_intentry 154
archx86_isr_interrupt155entry: isr_intentry 155
archx86_isr_interrupt156entry: isr_intentry 156
archx86_isr_interrupt157entry: isr_intentry 157
archx86_isr_interrupt158entry: isr_intentry 158
archx86_isr_interrupt159entry: isr_intentry 159
archx86_isr_interrupt160entry: isr_intentry 160
archx86_isr_interrupt161entry: isr_intentry 161
archx86_isr_interrupt162entry: isr_intentry 162
archx86_isr_interrupt163entry: isr_intentry 163
archx86_isr_interrupt164entry: isr_intentry 164
archx86_isr_interrupt165entry: isr_intentry 165
archx86_isr_interrupt166entry: isr_intentry 166
archx86_isr_interrupt167entry: isr_intentry 167
archx86_isr_interrupt168entry: isr_intentry 168
archx86_isr_interrupt169entry: isr_intentry 169
archx86_isr_interrupt170entry: isr_intentry 170
archx86_isr_interrupt171entry: isr_intentry 171
archx86_isr_interrupt172entry: isr_intentry 172
archx86_isr_interrupt173entry: isr_intentry 173
archx86_isr_interrupt174entry: isr_intentry 174
archx86_isr_interrupt175entry: isr_intentry 175
archx86_isr_interrupt176entry: isr_intentry 176
archx86_isr_interrupt177entry: isr_intentry 177
archx86_isr_interrupt178entry: isr_intentry 178
archx86_isr_interrupt179entry: isr_intentry 179
archx86_isr_interrupt180entry: isr_intentry 180
archx86_isr_interrupt181entry: isr_intentry 181
archx86_isr_interrupt182entry: isr_intentry 182
archx86_isr_interrupt183entry: isr_intentry 183
archx86_isr_interrupt184entry: isr_intentry 184
archx86_isr_interrupt185entry: isr_intentry 185
archx86_isr_interrupt186entry: isr_intentry 186
archx86_isr_interrupt187entry: isr_intentry 187
archx86_isr_interrupt188entry: isr_intentry 188
archx86_isr_interrupt189entry: isr_intentry 189
archx86_isr_interrupt190entry: isr_intentry 190
archx86_isr_interrupt191entry: isr_intentry 191
archx86_isr_interrupt192entry: isr_intentry 192
archx86_isr_interrupt193entry: isr_intentry 193
archx86_isr_interrupt194entry: isr_intentry 194
archx86_isr_interrupt195entry: isr_intentry 195
archx86_isr_interrupt196entry: isr_intentry 196
archx86_isr_interrupt197entry: isr_intentry 197
archx86_isr_interrupt198entry: isr_intentry 198
archx86_isr_interrupt199entry: isr_intentry 199
archx86_isr_interrupt200entry: isr_intentry 200
archx86_isr_interrupt201entry: isr_intentry 201
archx86_isr_interrupt202entry: isr_intentry 202
archx86_isr_interrupt203entry: isr_intentry 203
archx86_isr_interrupt204entry: isr_intentry 204
archx86_isr_interrupt205entry: isr_intentry 205
archx86_isr_interrupt206entry: isr_intentry 206
archx86_isr_interrupt207entry: isr_intentry 207
archx86_isr_interrupt208entry: isr_intentry 208
archx86_isr_interrupt209entry: isr_intentry 209
archx86_isr_interrupt210entry: isr_intentry 210
archx86_isr_interrupt211entry: isr_intentry 211
archx86_isr_interrupt212entry: isr_intentry 212
archx86_isr_interrupt213entry: isr_intentry 213
archx86_isr_interrupt214entry: isr_intentry 214
archx86_isr_interrupt215entry: isr_intentry 215
archx86_isr_interrupt216entry: isr_intentry 216
archx86_isr_interrupt217entry: isr_intentry 217
archx86_isr_interrupt218entry: isr_intentry 218
archx86_isr_interrupt219entry: isr_intentry 219
archx86_isr_interrupt220entry: isr_intentry 220
archx86_isr_interrupt221entry: isr_intentry 221
archx86_isr_interrupt222entry: isr_intentry 222
archx86_isr_interrupt223entry: isr_intentry 223
archx86_isr_interrupt224entry: isr_intentry 224
archx86_isr_interrupt225entry: isr_intentry 225
archx86_isr_interrupt226entry: isr_intentry 226
archx86_isr_interrupt227entry: isr_intentry 227
archx86_isr_interrupt228entry: isr_intentry 228
archx86_isr_interrupt229entry: isr_intentry 229
archx86_isr_interrupt230entry: isr_intentry 230
archx86_isr_interrupt231entry: isr_intentry 231
archx86_isr_interrupt232entry: isr_intentry 232
archx86_isr_interrupt233entry: isr_intentry 233
archx86_isr_interrupt234entry: isr_intentry 234
archx86_isr_interrupt235entry: isr_intentry 235
archx86_isr_interrupt236entry: isr_intentry 236
archx86_isr_interrupt237entry: isr_intentry 237
archx86_isr_interrupt238entry: isr_intentry 238
archx86_isr_interrupt239entry: isr_intentry 239
archx86_isr_interrupt240entry: isr_intentry 240
archx86_isr_interrupt241entry: isr_intentry 241
archx86_isr_interrupt242entry: isr_intentry 242
archx86_isr_interrupt243entry: isr_intentry 243
archx86_isr_interrupt244entry: isr_intentry 244
archx86_isr_interrupt245entry: isr_intentry 245
archx86_isr_interrupt246entry: isr_intentry 246
archx86_isr_interrupt247entry: isr_intentry 247
archx86_isr_interrupt248entry: isr_intentry 248
archx86_isr_interrupt249entry: isr_intentry 249
archx86_isr_interrupt250entry: isr_intentry 250
archx86_isr_interrupt251entry: isr_intentry 251
archx86_isr_interrupt252entry: isr_intentry 252
archx86_isr_interrupt253entry: isr_intentry 253
archx86_isr_interrupt254entry: isr_intentry 254
archx86_isr_interrupt255entry: isr_intentry 255
