#pragma once
#include <stdint.h>

extern int __ARCHI586_KERNEL_PHYSICAL_ADDRESS_BEGIN__;
extern int __ARCHI586_KERNEL_PHYSICAL_ADDRESS_END__;

#define ARCHI586_KERNEL_PHYSICAL_ADDRESS_BEGIN \
    (&__ARCHI586_KERNEL_PHYSICAL_ADDRESS_BEGIN__)
#define ARCHI586_KERNEL_PHYSICAL_ADDRESS_END \
    (&__ARCHI586_KERNEL_PHYSICAL_ADDRESS_END__)

extern int __ARCHI586_KERNEL_TEXT_BEGIN__;
extern int __ARCHI586_KERNEL_TEXT_END__;

#define ARCHI586_ARCH_KERNEL_TEXT_BEGIN  (&__ARCHI586_KERNEL_TEXT_BEGIN__)
#define ARCHI586_ARCH_KERNEL_TEXT_END    (&__ARCHI586_KERNEL_TEXT_END__)

extern int __ARCHI586_KERNEL_RO_AFTER_EARLY_INIT_BEGIN__;
extern int __ARCHI586_KERNEL_RO_AFTER_EARLY_INIT_END__;

#define ARCHI586_KERNEL_RO_AFTER_EARLY_INIT_BEGIN \
    (&__ARCHI586_KERNEL_RO_AFTER_EARLY_INIT_BEGIN__)
#define ARCHI586_KERNEL_RO_AFTER_EARLY_INIT_END \
    (&__ARCHI586_KERNEL_RO_AFTER_EARLY_INIT_END__)

extern int __ARCH_KERNEL_VIRTUAL_ADDRESS_BEGIN__;
extern int __ARCH_KERNEL_VIRTUAL_ADDRESS_END__;

#define ARCH_KERNEL_VIRTUAL_ADDRESS_BEGIN \
    (&__ARCH_KERNEL_VIRTUAL_ADDRESS_BEGIN__)
#define ARCH_KERNEL_VIRTUAL_ADDRESS_END \
    (&__ARCH_KERNEL_VIRTUAL_ADDRESS_END__)
