.global ArchI586_ISR_Exception0Entry,  ArchI586_ISR_Exception1Entry,  ArchI586_ISR_Exception2Entry,  ArchI586_ISR_Exception3Entry
.global ArchI586_ISR_Exception4Entry,  ArchI586_ISR_Exception5Entry,  ArchI586_ISR_Exception6Entry,  ArchI586_ISR_Exception7Entry
.global ArchI586_ISR_Exception8Entry,  ArchI586_ISR_Exception9Entry,  ArchI586_ISR_Exception10Entry, ArchI586_ISR_Exception11Entry
.global ArchI586_ISR_Exception12Entry, ArchI586_ISR_Exception13Entry, ArchI586_ISR_Exception14Entry, ArchI586_ISR_Exception15Entry
.global ArchI586_ISR_Exception16Entry, ArchI586_ISR_Exception17Entry, ArchI586_ISR_Exception18Entry, ArchI586_ISR_Exception19Entry
.global ArchI586_ISR_Exception20Entry, ArchI586_ISR_Exception21Entry, ArchI586_ISR_Exception22Entry, ArchI586_ISR_Exception23Entry
.global ArchI586_ISR_Exception24Entry, ArchI586_ISR_Exception25Entry, ArchI586_ISR_Exception26Entry, ArchI586_ISR_Exception27Entry
.global ArchI586_ISR_Exception28Entry, ArchI586_ISR_Exception29Entry, ArchI586_ISR_Exception30Entry, ArchI586_ISR_Exception31Entry

.global ArchI586_ISR_Interrupt32Entry,  ArchI586_ISR_Interrupt33Entry,  ArchI586_ISR_Interrupt34Entry,  ArchI586_ISR_Interrupt35Entry
.global ArchI586_ISR_Interrupt36Entry,  ArchI586_ISR_Interrupt37Entry,  ArchI586_ISR_Interrupt38Entry,  ArchI586_ISR_Interrupt39Entry
.global ArchI586_ISR_Interrupt40Entry,  ArchI586_ISR_Interrupt41Entry,  ArchI586_ISR_Interrupt42Entry,  ArchI586_ISR_Interrupt43Entry
.global ArchI586_ISR_Interrupt44Entry,  ArchI586_ISR_Interrupt45Entry,  ArchI586_ISR_Interrupt46Entry,  ArchI586_ISR_Interrupt47Entry
.global ArchI586_ISR_Interrupt48Entry,  ArchI586_ISR_Interrupt49Entry,  ArchI586_ISR_Interrupt50Entry,  ArchI586_ISR_Interrupt51Entry
.global ArchI586_ISR_Interrupt52Entry,  ArchI586_ISR_Interrupt53Entry,  ArchI586_ISR_Interrupt54Entry,  ArchI586_ISR_Interrupt55Entry
.global ArchI586_ISR_Interrupt56Entry,  ArchI586_ISR_Interrupt57Entry,  ArchI586_ISR_Interrupt58Entry,  ArchI586_ISR_Interrupt59Entry
.global ArchI586_ISR_Interrupt60Entry,  ArchI586_ISR_Interrupt61Entry,  ArchI586_ISR_Interrupt62Entry,  ArchI586_ISR_Interrupt63Entry
.global ArchI586_ISR_Interrupt64Entry,  ArchI586_ISR_Interrupt65Entry,  ArchI586_ISR_Interrupt66Entry,  ArchI586_ISR_Interrupt67Entry
.global ArchI586_ISR_Interrupt68Entry,  ArchI586_ISR_Interrupt69Entry,  ArchI586_ISR_Interrupt70Entry,  ArchI586_ISR_Interrupt71Entry
.global ArchI586_ISR_Interrupt72Entry,  ArchI586_ISR_Interrupt73Entry,  ArchI586_ISR_Interrupt74Entry,  ArchI586_ISR_Interrupt75Entry
.global ArchI586_ISR_Interrupt76Entry,  ArchI586_ISR_Interrupt77Entry,  ArchI586_ISR_Interrupt78Entry,  ArchI586_ISR_Interrupt79Entry
.global ArchI586_ISR_Interrupt80Entry,  ArchI586_ISR_Interrupt81Entry,  ArchI586_ISR_Interrupt82Entry,  ArchI586_ISR_Interrupt83Entry
.global ArchI586_ISR_Interrupt84Entry,  ArchI586_ISR_Interrupt85Entry,  ArchI586_ISR_Interrupt86Entry,  ArchI586_ISR_Interrupt87Entry
.global ArchI586_ISR_Interrupt88Entry,  ArchI586_ISR_Interrupt89Entry,  ArchI586_ISR_Interrupt90Entry,  ArchI586_ISR_Interrupt91Entry
.global ArchI586_ISR_Interrupt92Entry,  ArchI586_ISR_Interrupt93Entry,  ArchI586_ISR_Interrupt94Entry,  ArchI586_ISR_Interrupt95Entry
.global ArchI586_ISR_Interrupt96Entry,  ArchI586_ISR_Interrupt97Entry,  ArchI586_ISR_Interrupt98Entry,  ArchI586_ISR_Interrupt99Entry
.global ArchI586_ISR_Interrupt100Entry, ArchI586_ISR_Interrupt101Entry, ArchI586_ISR_Interrupt102Entry, ArchI586_ISR_Interrupt103Entry
.global ArchI586_ISR_Interrupt104Entry, ArchI586_ISR_Interrupt105Entry, ArchI586_ISR_Interrupt106Entry, ArchI586_ISR_Interrupt107Entry
.global ArchI586_ISR_Interrupt108Entry, ArchI586_ISR_Interrupt109Entry, ArchI586_ISR_Interrupt110Entry, ArchI586_ISR_Interrupt111Entry
.global ArchI586_ISR_Interrupt112Entry, ArchI586_ISR_Interrupt113Entry, ArchI586_ISR_Interrupt114Entry, ArchI586_ISR_Interrupt115Entry
.global ArchI586_ISR_Interrupt116Entry, ArchI586_ISR_Interrupt117Entry, ArchI586_ISR_Interrupt118Entry, ArchI586_ISR_Interrupt119Entry
.global ArchI586_ISR_Interrupt120Entry, ArchI586_ISR_Interrupt121Entry, ArchI586_ISR_Interrupt122Entry, ArchI586_ISR_Interrupt123Entry
.global ArchI586_ISR_Interrupt124Entry, ArchI586_ISR_Interrupt125Entry, ArchI586_ISR_Interrupt126Entry, ArchI586_ISR_Interrupt127Entry
.global ArchI586_ISR_Interrupt128Entry, ArchI586_ISR_Interrupt129Entry, ArchI586_ISR_Interrupt130Entry, ArchI586_ISR_Interrupt131Entry
.global ArchI586_ISR_Interrupt132Entry, ArchI586_ISR_Interrupt133Entry, ArchI586_ISR_Interrupt134Entry, ArchI586_ISR_Interrupt135Entry
.global ArchI586_ISR_Interrupt136Entry, ArchI586_ISR_Interrupt137Entry, ArchI586_ISR_Interrupt138Entry, ArchI586_ISR_Interrupt139Entry
.global ArchI586_ISR_Interrupt140Entry, ArchI586_ISR_Interrupt141Entry, ArchI586_ISR_Interrupt142Entry, ArchI586_ISR_Interrupt143Entry
.global ArchI586_ISR_Interrupt144Entry, ArchI586_ISR_Interrupt145Entry, ArchI586_ISR_Interrupt146Entry, ArchI586_ISR_Interrupt147Entry
.global ArchI586_ISR_Interrupt148Entry, ArchI586_ISR_Interrupt149Entry, ArchI586_ISR_Interrupt150Entry, ArchI586_ISR_Interrupt151Entry
.global ArchI586_ISR_Interrupt152Entry, ArchI586_ISR_Interrupt153Entry, ArchI586_ISR_Interrupt154Entry, ArchI586_ISR_Interrupt155Entry
.global ArchI586_ISR_Interrupt156Entry, ArchI586_ISR_Interrupt157Entry, ArchI586_ISR_Interrupt158Entry, ArchI586_ISR_Interrupt159Entry
.global ArchI586_ISR_Interrupt160Entry, ArchI586_ISR_Interrupt161Entry, ArchI586_ISR_Interrupt162Entry, ArchI586_ISR_Interrupt163Entry
.global ArchI586_ISR_Interrupt164Entry, ArchI586_ISR_Interrupt165Entry, ArchI586_ISR_Interrupt166Entry, ArchI586_ISR_Interrupt167Entry
.global ArchI586_ISR_Interrupt168Entry, ArchI586_ISR_Interrupt169Entry, ArchI586_ISR_Interrupt170Entry, ArchI586_ISR_Interrupt171Entry
.global ArchI586_ISR_Interrupt172Entry, ArchI586_ISR_Interrupt173Entry, ArchI586_ISR_Interrupt174Entry, ArchI586_ISR_Interrupt175Entry
.global ArchI586_ISR_Interrupt176Entry, ArchI586_ISR_Interrupt177Entry, ArchI586_ISR_Interrupt178Entry, ArchI586_ISR_Interrupt179Entry
.global ArchI586_ISR_Interrupt180Entry, ArchI586_ISR_Interrupt181Entry, ArchI586_ISR_Interrupt182Entry, ArchI586_ISR_Interrupt183Entry
.global ArchI586_ISR_Interrupt184Entry, ArchI586_ISR_Interrupt185Entry, ArchI586_ISR_Interrupt186Entry, ArchI586_ISR_Interrupt187Entry
.global ArchI586_ISR_Interrupt188Entry, ArchI586_ISR_Interrupt189Entry, ArchI586_ISR_Interrupt190Entry, ArchI586_ISR_Interrupt191Entry
.global ArchI586_ISR_Interrupt192Entry, ArchI586_ISR_Interrupt193Entry, ArchI586_ISR_Interrupt194Entry, ArchI586_ISR_Interrupt195Entry
.global ArchI586_ISR_Interrupt196Entry, ArchI586_ISR_Interrupt197Entry, ArchI586_ISR_Interrupt198Entry, ArchI586_ISR_Interrupt199Entry
.global ArchI586_ISR_Interrupt200Entry, ArchI586_ISR_Interrupt201Entry, ArchI586_ISR_Interrupt202Entry, ArchI586_ISR_Interrupt203Entry
.global ArchI586_ISR_Interrupt204Entry, ArchI586_ISR_Interrupt205Entry, ArchI586_ISR_Interrupt206Entry, ArchI586_ISR_Interrupt207Entry
.global ArchI586_ISR_Interrupt208Entry, ArchI586_ISR_Interrupt209Entry, ArchI586_ISR_Interrupt210Entry, ArchI586_ISR_Interrupt211Entry
.global ArchI586_ISR_Interrupt212Entry, ArchI586_ISR_Interrupt213Entry, ArchI586_ISR_Interrupt214Entry, ArchI586_ISR_Interrupt215Entry
.global ArchI586_ISR_Interrupt216Entry, ArchI586_ISR_Interrupt217Entry, ArchI586_ISR_Interrupt218Entry, ArchI586_ISR_Interrupt219Entry
.global ArchI586_ISR_Interrupt220Entry, ArchI586_ISR_Interrupt221Entry, ArchI586_ISR_Interrupt222Entry, ArchI586_ISR_Interrupt223Entry
.global ArchI586_ISR_Interrupt224Entry, ArchI586_ISR_Interrupt225Entry, ArchI586_ISR_Interrupt226Entry, ArchI586_ISR_Interrupt227Entry
.global ArchI586_ISR_Interrupt228Entry, ArchI586_ISR_Interrupt229Entry, ArchI586_ISR_Interrupt230Entry, ArchI586_ISR_Interrupt231Entry
.global ArchI586_ISR_Interrupt232Entry, ArchI586_ISR_Interrupt233Entry, ArchI586_ISR_Interrupt234Entry, ArchI586_ISR_Interrupt235Entry
.global ArchI586_ISR_Interrupt236Entry, ArchI586_ISR_Interrupt237Entry, ArchI586_ISR_Interrupt238Entry, ArchI586_ISR_Interrupt239Entry
.global ArchI586_ISR_Interrupt240Entry, ArchI586_ISR_Interrupt241Entry, ArchI586_ISR_Interrupt242Entry, ArchI586_ISR_Interrupt243Entry
.global ArchI586_ISR_Interrupt244Entry, ArchI586_ISR_Interrupt245Entry, ArchI586_ISR_Interrupt246Entry, ArchI586_ISR_Interrupt247Entry
.global ArchI586_ISR_Interrupt248Entry, ArchI586_ISR_Interrupt249Entry, ArchI586_ISR_Interrupt250Entry, ArchI586_ISR_Interrupt251Entry
.global ArchI586_ISR_Interrupt252Entry, ArchI586_ISR_Interrupt253Entry, ArchI586_ISR_Interrupt254Entry, ArchI586_ISR_Interrupt255Entry

.macro isr_exc_header
    cli
.endm

.macro push_fake_code
    push $0
.endm

.macro save_regs
    pusha
    mov %ds, %eax
    push %eax
    mov %es, %eax
    push %eax
    mov %fs, %eax
    push %eax 
    mov %gs, %eax
    push %eax 
.endm

.macro restore_regs
    add $8, %esp /* Skip FS and GS */
    pop %eax
    mov %eax, %es
    pop %eax
    mov %eax, %ds
    popa
.endm

.macro isr_footer
    add $4, %esp
    iret
.endm

.macro call_handler n
    mov %esp, %ebx
    /* Align the stack */
    and $~0x0F, %esp
    /* Call the handler */
    push %ebx /* Arg 1 */
    push $\n  /* Arg 0 */
    call TrapManager_Trap
    /* Restore ESP */
    mov %ebx, %esp
.endm

.macro isr_excentry n
    isr_exc_header
    save_regs
    call_handler \n
    restore_regs
    isr_footer 
.endm

.macro isr_excentry_nocode n
    isr_exc_header
    push_fake_code
    save_regs
    call_handler \n
    restore_regs
    isr_footer 
.endm

.macro isr_intentry n
    push_fake_code
    save_regs
    call_handler \n
    restore_regs
    isr_footer 
.endm

ArchI586_ISR_Exception0Entry:  isr_excentry_nocode 0
ArchI586_ISR_Exception1Entry:  isr_excentry_nocode 1
ArchI586_ISR_Exception2Entry:  isr_excentry_nocode 2
ArchI586_ISR_Exception3Entry:  isr_excentry_nocode 3
ArchI586_ISR_Exception4Entry:  isr_excentry_nocode 4
ArchI586_ISR_Exception5Entry:  isr_excentry_nocode 5
ArchI586_ISR_Exception6Entry:  isr_excentry_nocode 6
/* ArchI586_ISR_Exception7Entry:  isr_excentry_nocode 7 */
ArchI586_ISR_Exception7Entry:  jmp ArchI586_ISR_Exception7Entry
ArchI586_ISR_Exception8Entry:  isr_excentry        8
ArchI586_ISR_Exception9Entry:  isr_excentry_nocode 9
ArchI586_ISR_Exception10Entry: isr_excentry        10
ArchI586_ISR_Exception11Entry: isr_excentry        11
ArchI586_ISR_Exception12Entry: isr_excentry        12
ArchI586_ISR_Exception13Entry: isr_excentry        13
ArchI586_ISR_Exception14Entry: isr_excentry        14
ArchI586_ISR_Exception15Entry: isr_excentry_nocode 15
ArchI586_ISR_Exception16Entry: isr_excentry_nocode 16
ArchI586_ISR_Exception17Entry: isr_excentry        17
ArchI586_ISR_Exception18Entry: isr_excentry_nocode 18
ArchI586_ISR_Exception19Entry: isr_excentry_nocode 19
ArchI586_ISR_Exception20Entry: isr_excentry_nocode 20
ArchI586_ISR_Exception21Entry: isr_excentry        21
ArchI586_ISR_Exception22Entry: isr_excentry_nocode 22
ArchI586_ISR_Exception23Entry: isr_excentry_nocode 23
ArchI586_ISR_Exception24Entry: isr_excentry_nocode 24
ArchI586_ISR_Exception25Entry: isr_excentry_nocode 25
ArchI586_ISR_Exception26Entry: isr_excentry_nocode 26
ArchI586_ISR_Exception27Entry: isr_excentry_nocode 27
ArchI586_ISR_Exception28Entry: isr_excentry_nocode 28
ArchI586_ISR_Exception29Entry: isr_excentry        29
ArchI586_ISR_Exception30Entry: isr_excentry        30
ArchI586_ISR_Exception31Entry: isr_excentry_nocode 31

ArchI586_ISR_Interrupt32Entry:  isr_intentry 32
ArchI586_ISR_Interrupt33Entry:  isr_intentry 33
ArchI586_ISR_Interrupt34Entry:  isr_intentry 34
ArchI586_ISR_Interrupt35Entry:  isr_intentry 35
ArchI586_ISR_Interrupt36Entry:  isr_intentry 36
ArchI586_ISR_Interrupt37Entry:  isr_intentry 37
ArchI586_ISR_Interrupt38Entry:  isr_intentry 38
ArchI586_ISR_Interrupt39Entry:  isr_intentry 39
ArchI586_ISR_Interrupt40Entry:  isr_intentry 40
ArchI586_ISR_Interrupt41Entry:  isr_intentry 41
ArchI586_ISR_Interrupt42Entry:  isr_intentry 42
ArchI586_ISR_Interrupt43Entry:  isr_intentry 43
ArchI586_ISR_Interrupt44Entry:  isr_intentry 44
ArchI586_ISR_Interrupt45Entry:  isr_intentry 45
ArchI586_ISR_Interrupt46Entry:  isr_intentry 46
ArchI586_ISR_Interrupt47Entry:  isr_intentry 47
ArchI586_ISR_Interrupt48Entry:  isr_intentry 48
ArchI586_ISR_Interrupt49Entry:  isr_intentry 49
ArchI586_ISR_Interrupt50Entry:  isr_intentry 50
ArchI586_ISR_Interrupt51Entry:  isr_intentry 51
ArchI586_ISR_Interrupt52Entry:  isr_intentry 52
ArchI586_ISR_Interrupt53Entry:  isr_intentry 53
ArchI586_ISR_Interrupt54Entry:  isr_intentry 54
ArchI586_ISR_Interrupt55Entry:  isr_intentry 55
ArchI586_ISR_Interrupt56Entry:  isr_intentry 56
ArchI586_ISR_Interrupt57Entry:  isr_intentry 57
ArchI586_ISR_Interrupt58Entry:  isr_intentry 58
ArchI586_ISR_Interrupt59Entry:  isr_intentry 59
ArchI586_ISR_Interrupt60Entry:  isr_intentry 60
ArchI586_ISR_Interrupt61Entry:  isr_intentry 61
ArchI586_ISR_Interrupt62Entry:  isr_intentry 62
ArchI586_ISR_Interrupt63Entry:  isr_intentry 63
ArchI586_ISR_Interrupt64Entry:  isr_intentry 64
ArchI586_ISR_Interrupt65Entry:  isr_intentry 65
ArchI586_ISR_Interrupt66Entry:  isr_intentry 66
ArchI586_ISR_Interrupt67Entry:  isr_intentry 67
ArchI586_ISR_Interrupt68Entry:  isr_intentry 68
ArchI586_ISR_Interrupt69Entry:  isr_intentry 69
ArchI586_ISR_Interrupt70Entry:  isr_intentry 70
ArchI586_ISR_Interrupt71Entry:  isr_intentry 71
ArchI586_ISR_Interrupt72Entry:  isr_intentry 72
ArchI586_ISR_Interrupt73Entry:  isr_intentry 73
ArchI586_ISR_Interrupt74Entry:  isr_intentry 74
ArchI586_ISR_Interrupt75Entry:  isr_intentry 75
ArchI586_ISR_Interrupt76Entry:  isr_intentry 76
ArchI586_ISR_Interrupt77Entry:  isr_intentry 77
ArchI586_ISR_Interrupt78Entry:  isr_intentry 78
ArchI586_ISR_Interrupt79Entry:  isr_intentry 79
ArchI586_ISR_Interrupt80Entry:  isr_intentry 80
ArchI586_ISR_Interrupt81Entry:  isr_intentry 81
ArchI586_ISR_Interrupt82Entry:  isr_intentry 82
ArchI586_ISR_Interrupt83Entry:  isr_intentry 83
ArchI586_ISR_Interrupt84Entry:  isr_intentry 84
ArchI586_ISR_Interrupt85Entry:  isr_intentry 85
ArchI586_ISR_Interrupt86Entry:  isr_intentry 86
ArchI586_ISR_Interrupt87Entry:  isr_intentry 87
ArchI586_ISR_Interrupt88Entry:  isr_intentry 88
ArchI586_ISR_Interrupt89Entry:  isr_intentry 89
ArchI586_ISR_Interrupt90Entry:  isr_intentry 90
ArchI586_ISR_Interrupt91Entry:  isr_intentry 91
ArchI586_ISR_Interrupt92Entry:  isr_intentry 92
ArchI586_ISR_Interrupt93Entry:  isr_intentry 93
ArchI586_ISR_Interrupt94Entry:  isr_intentry 94
ArchI586_ISR_Interrupt95Entry:  isr_intentry 95
ArchI586_ISR_Interrupt96Entry:  isr_intentry 96
ArchI586_ISR_Interrupt97Entry:  isr_intentry 97
ArchI586_ISR_Interrupt98Entry:  isr_intentry 98
ArchI586_ISR_Interrupt99Entry:  isr_intentry 99
ArchI586_ISR_Interrupt100Entry: isr_intentry 100
ArchI586_ISR_Interrupt101Entry: isr_intentry 101
ArchI586_ISR_Interrupt102Entry: isr_intentry 102
ArchI586_ISR_Interrupt103Entry: isr_intentry 103
ArchI586_ISR_Interrupt104Entry: isr_intentry 104
ArchI586_ISR_Interrupt105Entry: isr_intentry 105
ArchI586_ISR_Interrupt106Entry: isr_intentry 106
ArchI586_ISR_Interrupt107Entry: isr_intentry 107
ArchI586_ISR_Interrupt108Entry: isr_intentry 108
ArchI586_ISR_Interrupt109Entry: isr_intentry 109
ArchI586_ISR_Interrupt110Entry: isr_intentry 110
ArchI586_ISR_Interrupt111Entry: isr_intentry 111
ArchI586_ISR_Interrupt112Entry: isr_intentry 112
ArchI586_ISR_Interrupt113Entry: isr_intentry 113
ArchI586_ISR_Interrupt114Entry: isr_intentry 114
ArchI586_ISR_Interrupt115Entry: isr_intentry 115
ArchI586_ISR_Interrupt116Entry: isr_intentry 116
ArchI586_ISR_Interrupt117Entry: isr_intentry 117
ArchI586_ISR_Interrupt118Entry: isr_intentry 118
ArchI586_ISR_Interrupt119Entry: isr_intentry 119
ArchI586_ISR_Interrupt120Entry: isr_intentry 120
ArchI586_ISR_Interrupt121Entry: isr_intentry 121
ArchI586_ISR_Interrupt122Entry: isr_intentry 122
ArchI586_ISR_Interrupt123Entry: isr_intentry 123
ArchI586_ISR_Interrupt124Entry: isr_intentry 124
ArchI586_ISR_Interrupt125Entry: isr_intentry 125
ArchI586_ISR_Interrupt126Entry: isr_intentry 126
ArchI586_ISR_Interrupt127Entry: isr_intentry 127
ArchI586_ISR_Interrupt128Entry: isr_intentry 128
ArchI586_ISR_Interrupt129Entry: isr_intentry 129
ArchI586_ISR_Interrupt130Entry: isr_intentry 130
ArchI586_ISR_Interrupt131Entry: isr_intentry 131
ArchI586_ISR_Interrupt132Entry: isr_intentry 132
ArchI586_ISR_Interrupt133Entry: isr_intentry 133
ArchI586_ISR_Interrupt134Entry: isr_intentry 134
ArchI586_ISR_Interrupt135Entry: isr_intentry 135
ArchI586_ISR_Interrupt136Entry: isr_intentry 136
ArchI586_ISR_Interrupt137Entry: isr_intentry 137
ArchI586_ISR_Interrupt138Entry: isr_intentry 138
ArchI586_ISR_Interrupt139Entry: isr_intentry 139
ArchI586_ISR_Interrupt140Entry: isr_intentry 140
ArchI586_ISR_Interrupt141Entry: isr_intentry 141
ArchI586_ISR_Interrupt142Entry: isr_intentry 142
ArchI586_ISR_Interrupt143Entry: isr_intentry 143
ArchI586_ISR_Interrupt144Entry: isr_intentry 144
ArchI586_ISR_Interrupt145Entry: isr_intentry 145
ArchI586_ISR_Interrupt146Entry: isr_intentry 146
ArchI586_ISR_Interrupt147Entry: isr_intentry 147
ArchI586_ISR_Interrupt148Entry: isr_intentry 148
ArchI586_ISR_Interrupt149Entry: isr_intentry 149
ArchI586_ISR_Interrupt150Entry: isr_intentry 150
ArchI586_ISR_Interrupt151Entry: isr_intentry 151
ArchI586_ISR_Interrupt152Entry: isr_intentry 152
ArchI586_ISR_Interrupt153Entry: isr_intentry 153
ArchI586_ISR_Interrupt154Entry: isr_intentry 154
ArchI586_ISR_Interrupt155Entry: isr_intentry 155
ArchI586_ISR_Interrupt156Entry: isr_intentry 156
ArchI586_ISR_Interrupt157Entry: isr_intentry 157
ArchI586_ISR_Interrupt158Entry: isr_intentry 158
ArchI586_ISR_Interrupt159Entry: isr_intentry 159
ArchI586_ISR_Interrupt160Entry: isr_intentry 160
ArchI586_ISR_Interrupt161Entry: isr_intentry 161
ArchI586_ISR_Interrupt162Entry: isr_intentry 162
ArchI586_ISR_Interrupt163Entry: isr_intentry 163
ArchI586_ISR_Interrupt164Entry: isr_intentry 164
ArchI586_ISR_Interrupt165Entry: isr_intentry 165
ArchI586_ISR_Interrupt166Entry: isr_intentry 166
ArchI586_ISR_Interrupt167Entry: isr_intentry 167
ArchI586_ISR_Interrupt168Entry: isr_intentry 168
ArchI586_ISR_Interrupt169Entry: isr_intentry 169
ArchI586_ISR_Interrupt170Entry: isr_intentry 170
ArchI586_ISR_Interrupt171Entry: isr_intentry 171
ArchI586_ISR_Interrupt172Entry: isr_intentry 172
ArchI586_ISR_Interrupt173Entry: isr_intentry 173
ArchI586_ISR_Interrupt174Entry: isr_intentry 174
ArchI586_ISR_Interrupt175Entry: isr_intentry 175
ArchI586_ISR_Interrupt176Entry: isr_intentry 176
ArchI586_ISR_Interrupt177Entry: isr_intentry 177
ArchI586_ISR_Interrupt178Entry: isr_intentry 178
ArchI586_ISR_Interrupt179Entry: isr_intentry 179
ArchI586_ISR_Interrupt180Entry: isr_intentry 180
ArchI586_ISR_Interrupt181Entry: isr_intentry 181
ArchI586_ISR_Interrupt182Entry: isr_intentry 182
ArchI586_ISR_Interrupt183Entry: isr_intentry 183
ArchI586_ISR_Interrupt184Entry: isr_intentry 184
ArchI586_ISR_Interrupt185Entry: isr_intentry 185
ArchI586_ISR_Interrupt186Entry: isr_intentry 186
ArchI586_ISR_Interrupt187Entry: isr_intentry 187
ArchI586_ISR_Interrupt188Entry: isr_intentry 188
ArchI586_ISR_Interrupt189Entry: isr_intentry 189
ArchI586_ISR_Interrupt190Entry: isr_intentry 190
ArchI586_ISR_Interrupt191Entry: isr_intentry 191
ArchI586_ISR_Interrupt192Entry: isr_intentry 192
ArchI586_ISR_Interrupt193Entry: isr_intentry 193
ArchI586_ISR_Interrupt194Entry: isr_intentry 194
ArchI586_ISR_Interrupt195Entry: isr_intentry 195
ArchI586_ISR_Interrupt196Entry: isr_intentry 196
ArchI586_ISR_Interrupt197Entry: isr_intentry 197
ArchI586_ISR_Interrupt198Entry: isr_intentry 198
ArchI586_ISR_Interrupt199Entry: isr_intentry 199
ArchI586_ISR_Interrupt200Entry: isr_intentry 200
ArchI586_ISR_Interrupt201Entry: isr_intentry 201
ArchI586_ISR_Interrupt202Entry: isr_intentry 202
ArchI586_ISR_Interrupt203Entry: isr_intentry 203
ArchI586_ISR_Interrupt204Entry: isr_intentry 204
ArchI586_ISR_Interrupt205Entry: isr_intentry 205
ArchI586_ISR_Interrupt206Entry: isr_intentry 206
ArchI586_ISR_Interrupt207Entry: isr_intentry 207
ArchI586_ISR_Interrupt208Entry: isr_intentry 208
ArchI586_ISR_Interrupt209Entry: isr_intentry 209
ArchI586_ISR_Interrupt210Entry: isr_intentry 210
ArchI586_ISR_Interrupt211Entry: isr_intentry 211
ArchI586_ISR_Interrupt212Entry: isr_intentry 212
ArchI586_ISR_Interrupt213Entry: isr_intentry 213
ArchI586_ISR_Interrupt214Entry: isr_intentry 214
ArchI586_ISR_Interrupt215Entry: isr_intentry 215
ArchI586_ISR_Interrupt216Entry: isr_intentry 216
ArchI586_ISR_Interrupt217Entry: isr_intentry 217
ArchI586_ISR_Interrupt218Entry: isr_intentry 218
ArchI586_ISR_Interrupt219Entry: isr_intentry 219
ArchI586_ISR_Interrupt220Entry: isr_intentry 220
ArchI586_ISR_Interrupt221Entry: isr_intentry 221
ArchI586_ISR_Interrupt222Entry: isr_intentry 222
ArchI586_ISR_Interrupt223Entry: isr_intentry 223
ArchI586_ISR_Interrupt224Entry: isr_intentry 224
ArchI586_ISR_Interrupt225Entry: isr_intentry 225
ArchI586_ISR_Interrupt226Entry: isr_intentry 226
ArchI586_ISR_Interrupt227Entry: isr_intentry 227
ArchI586_ISR_Interrupt228Entry: isr_intentry 228
ArchI586_ISR_Interrupt229Entry: isr_intentry 229
ArchI586_ISR_Interrupt230Entry: isr_intentry 230
ArchI586_ISR_Interrupt231Entry: isr_intentry 231
ArchI586_ISR_Interrupt232Entry: isr_intentry 232
ArchI586_ISR_Interrupt233Entry: isr_intentry 233
ArchI586_ISR_Interrupt234Entry: isr_intentry 234
ArchI586_ISR_Interrupt235Entry: isr_intentry 235
ArchI586_ISR_Interrupt236Entry: isr_intentry 236
ArchI586_ISR_Interrupt237Entry: isr_intentry 237
ArchI586_ISR_Interrupt238Entry: isr_intentry 238
ArchI586_ISR_Interrupt239Entry: isr_intentry 239
ArchI586_ISR_Interrupt240Entry: isr_intentry 240
ArchI586_ISR_Interrupt241Entry: isr_intentry 241
ArchI586_ISR_Interrupt242Entry: isr_intentry 242
ArchI586_ISR_Interrupt243Entry: isr_intentry 243
ArchI586_ISR_Interrupt244Entry: isr_intentry 244
ArchI586_ISR_Interrupt245Entry: isr_intentry 245
ArchI586_ISR_Interrupt246Entry: isr_intentry 246
ArchI586_ISR_Interrupt247Entry: isr_intentry 247
ArchI586_ISR_Interrupt248Entry: isr_intentry 248
ArchI586_ISR_Interrupt249Entry: isr_intentry 249
ArchI586_ISR_Interrupt250Entry: isr_intentry 250
ArchI586_ISR_Interrupt251Entry: isr_intentry 251
ArchI586_ISR_Interrupt252Entry: isr_intentry 252
ArchI586_ISR_Interrupt253Entry: isr_intentry 253
ArchI586_ISR_Interrupt254Entry: isr_intentry 254
ArchI586_ISR_Interrupt255Entry: isr_intentry 255
