.global archi586_isr_exception0entry,  archi586_isr_exception1entry,  archi586_isr_exception2entry,  archi586_isr_exception3entry
.global archi586_isr_exception4entry,  archi586_isr_exception5entry,  archi586_isr_exception6entry,  archi586_isr_exception7entry
.global archi586_isr_exception8entry,  archi586_isr_exception9entry,  archi586_isr_exception10entry, archi586_isr_exception11entry
.global archi586_isr_exception12entry, archi586_isr_exception13entry, archi586_isr_exception14entry, archi586_isr_exception15entry
.global archi586_isr_exception16entry, archi586_isr_exception17entry, archi586_isr_exception18entry, archi586_isr_exception19entry
.global archi586_isr_exception20entry, archi586_isr_exception21entry, archi586_isr_exception22entry, archi586_isr_exception23entry
.global archi586_isr_exception24entry, archi586_isr_exception25entry, archi586_isr_exception26entry, archi586_isr_exception27entry
.global archi586_isr_exception28entry, archi586_isr_exception29entry, archi586_isr_exception30entry, archi586_isr_exception31entry

.global archi586_isr_interrupt32entry,  archi586_isr_interrupt33entry,  archi586_isr_interrupt34entry,  archi586_isr_interrupt35entry
.global archi586_isr_interrupt36entry,  archi586_isr_interrupt37entry,  archi586_isr_interrupt38entry,  archi586_isr_interrupt39entry
.global archi586_isr_interrupt40entry,  archi586_isr_interrupt41entry,  archi586_isr_interrupt42entry,  archi586_isr_interrupt43entry
.global archi586_isr_interrupt44entry,  archi586_isr_interrupt45entry,  archi586_isr_interrupt46entry,  archi586_isr_interrupt47entry
.global archi586_isr_interrupt48entry,  archi586_isr_interrupt49entry,  archi586_isr_interrupt50entry,  archi586_isr_interrupt51entry
.global archi586_isr_interrupt52entry,  archi586_isr_interrupt53entry,  archi586_isr_interrupt54entry,  archi586_isr_interrupt55entry
.global archi586_isr_interrupt56entry,  archi586_isr_interrupt57entry,  archi586_isr_interrupt58entry,  archi586_isr_interrupt59entry
.global archi586_isr_interrupt60entry,  archi586_isr_interrupt61entry,  archi586_isr_interrupt62entry,  archi586_isr_interrupt63entry
.global archi586_isr_interrupt64entry,  archi586_isr_interrupt65entry,  archi586_isr_interrupt66entry,  archi586_isr_interrupt67entry
.global archi586_isr_interrupt68entry,  archi586_isr_interrupt69entry,  archi586_isr_interrupt70entry,  archi586_isr_interrupt71entry
.global archi586_isr_interrupt72entry,  archi586_isr_interrupt73entry,  archi586_isr_interrupt74entry,  archi586_isr_interrupt75entry
.global archi586_isr_interrupt76entry,  archi586_isr_interrupt77entry,  archi586_isr_interrupt78entry,  archi586_isr_interrupt79entry
.global archi586_isr_interrupt80entry,  archi586_isr_interrupt81entry,  archi586_isr_interrupt82entry,  archi586_isr_interrupt83entry
.global archi586_isr_interrupt84entry,  archi586_isr_interrupt85entry,  archi586_isr_interrupt86entry,  archi586_isr_interrupt87entry
.global archi586_isr_interrupt88entry,  archi586_isr_interrupt89entry,  archi586_isr_interrupt90entry,  archi586_isr_interrupt91entry
.global archi586_isr_interrupt92entry,  archi586_isr_interrupt93entry,  archi586_isr_interrupt94entry,  archi586_isr_interrupt95entry
.global archi586_isr_interrupt96entry,  archi586_isr_interrupt97entry,  archi586_isr_interrupt98entry,  archi586_isr_interrupt99entry
.global archi586_isr_interrupt100entry, archi586_isr_interrupt101entry, archi586_isr_interrupt102entry, archi586_isr_interrupt103entry
.global archi586_isr_interrupt104entry, archi586_isr_interrupt105entry, archi586_isr_interrupt106entry, archi586_isr_interrupt107entry
.global archi586_isr_interrupt108entry, archi586_isr_interrupt109entry, archi586_isr_interrupt110entry, archi586_isr_interrupt111entry
.global archi586_isr_interrupt112entry, archi586_isr_interrupt113entry, archi586_isr_interrupt114entry, archi586_isr_interrupt115entry
.global archi586_isr_interrupt116entry, archi586_isr_interrupt117entry, archi586_isr_interrupt118entry, archi586_isr_interrupt119entry
.global archi586_isr_interrupt120entry, archi586_isr_interrupt121entry, archi586_isr_interrupt122entry, archi586_isr_interrupt123entry
.global archi586_isr_interrupt124entry, archi586_isr_interrupt125entry, archi586_isr_interrupt126entry, archi586_isr_interrupt127entry
.global archi586_isr_interrupt128entry, archi586_isr_interrupt129entry, archi586_isr_interrupt130entry, archi586_isr_interrupt131entry
.global archi586_isr_interrupt132entry, archi586_isr_interrupt133entry, archi586_isr_interrupt134entry, archi586_isr_interrupt135entry
.global archi586_isr_interrupt136entry, archi586_isr_interrupt137entry, archi586_isr_interrupt138entry, archi586_isr_interrupt139entry
.global archi586_isr_interrupt140entry, archi586_isr_interrupt141entry, archi586_isr_interrupt142entry, archi586_isr_interrupt143entry
.global archi586_isr_interrupt144entry, archi586_isr_interrupt145entry, archi586_isr_interrupt146entry, archi586_isr_interrupt147entry
.global archi586_isr_interrupt148entry, archi586_isr_interrupt149entry, archi586_isr_interrupt150entry, archi586_isr_interrupt151entry
.global archi586_isr_interrupt152entry, archi586_isr_interrupt153entry, archi586_isr_interrupt154entry, archi586_isr_interrupt155entry
.global archi586_isr_interrupt156entry, archi586_isr_interrupt157entry, archi586_isr_interrupt158entry, archi586_isr_interrupt159entry
.global archi586_isr_interrupt160entry, archi586_isr_interrupt161entry, archi586_isr_interrupt162entry, archi586_isr_interrupt163entry
.global archi586_isr_interrupt164entry, archi586_isr_interrupt165entry, archi586_isr_interrupt166entry, archi586_isr_interrupt167entry
.global archi586_isr_interrupt168entry, archi586_isr_interrupt169entry, archi586_isr_interrupt170entry, archi586_isr_interrupt171entry
.global archi586_isr_interrupt172entry, archi586_isr_interrupt173entry, archi586_isr_interrupt174entry, archi586_isr_interrupt175entry
.global archi586_isr_interrupt176entry, archi586_isr_interrupt177entry, archi586_isr_interrupt178entry, archi586_isr_interrupt179entry
.global archi586_isr_interrupt180entry, archi586_isr_interrupt181entry, archi586_isr_interrupt182entry, archi586_isr_interrupt183entry
.global archi586_isr_interrupt184entry, archi586_isr_interrupt185entry, archi586_isr_interrupt186entry, archi586_isr_interrupt187entry
.global archi586_isr_interrupt188entry, archi586_isr_interrupt189entry, archi586_isr_interrupt190entry, archi586_isr_interrupt191entry
.global archi586_isr_interrupt192entry, archi586_isr_interrupt193entry, archi586_isr_interrupt194entry, archi586_isr_interrupt195entry
.global archi586_isr_interrupt196entry, archi586_isr_interrupt197entry, archi586_isr_interrupt198entry, archi586_isr_interrupt199entry
.global archi586_isr_interrupt200entry, archi586_isr_interrupt201entry, archi586_isr_interrupt202entry, archi586_isr_interrupt203entry
.global archi586_isr_interrupt204entry, archi586_isr_interrupt205entry, archi586_isr_interrupt206entry, archi586_isr_interrupt207entry
.global archi586_isr_interrupt208entry, archi586_isr_interrupt209entry, archi586_isr_interrupt210entry, archi586_isr_interrupt211entry
.global archi586_isr_interrupt212entry, archi586_isr_interrupt213entry, archi586_isr_interrupt214entry, archi586_isr_interrupt215entry
.global archi586_isr_interrupt216entry, archi586_isr_interrupt217entry, archi586_isr_interrupt218entry, archi586_isr_interrupt219entry
.global archi586_isr_interrupt220entry, archi586_isr_interrupt221entry, archi586_isr_interrupt222entry, archi586_isr_interrupt223entry
.global archi586_isr_interrupt224entry, archi586_isr_interrupt225entry, archi586_isr_interrupt226entry, archi586_isr_interrupt227entry
.global archi586_isr_interrupt228entry, archi586_isr_interrupt229entry, archi586_isr_interrupt230entry, archi586_isr_interrupt231entry
.global archi586_isr_interrupt232entry, archi586_isr_interrupt233entry, archi586_isr_interrupt234entry, archi586_isr_interrupt235entry
.global archi586_isr_interrupt236entry, archi586_isr_interrupt237entry, archi586_isr_interrupt238entry, archi586_isr_interrupt239entry
.global archi586_isr_interrupt240entry, archi586_isr_interrupt241entry, archi586_isr_interrupt242entry, archi586_isr_interrupt243entry
.global archi586_isr_interrupt244entry, archi586_isr_interrupt245entry, archi586_isr_interrupt246entry, archi586_isr_interrupt247entry
.global archi586_isr_interrupt248entry, archi586_isr_interrupt249entry, archi586_isr_interrupt250entry, archi586_isr_interrupt251entry
.global archi586_isr_interrupt252entry, archi586_isr_interrupt253entry, archi586_isr_interrupt254entry, archi586_isr_interrupt255entry

.macro isr_exc_header
    cli
.endm

.macro push_fake_code
    push $0
.endm

.macro save_regs
    pusha
    mov %ds, %eax
    push %eax
    mov %es, %eax
    push %eax
    mov %fs, %eax
    push %eax 
    mov %gs, %eax
    push %eax 
.endm

.macro restore_regs
    add $8, %esp /* Skip FS and GS */
    pop %eax
    mov %eax, %es
    pop %eax
    mov %eax, %ds
    popa
.endm

.macro isr_footer
    add $4, %esp
    iret
.endm

.macro call_handler n
    mov %esp, %ebx
    /* Align the stack */
    and $~0x0F, %esp
    /* Call the handler */
    push %ebx /* Arg 1 */
    push $\n  /* Arg 0 */
    call trapmanager_trap
    /* Restore ESP */
    mov %ebx, %esp
.endm

.macro isr_excentry n
    isr_exc_header
    save_regs
    call_handler \n
    restore_regs
    isr_footer 
.endm

.macro isr_excentry_nocode n
    isr_exc_header
    push_fake_code
    save_regs
    call_handler \n
    restore_regs
    isr_footer 
.endm

.macro isr_intentry n
    push_fake_code
    save_regs
    call_handler \n
    restore_regs
    isr_footer 
.endm

archi586_isr_exception0entry:  isr_excentry_nocode 0
archi586_isr_exception1entry:  isr_excentry_nocode 1
archi586_isr_exception2entry:  isr_excentry_nocode 2
archi586_isr_exception3entry:  isr_excentry_nocode 3
archi586_isr_exception4entry:  isr_excentry_nocode 4
archi586_isr_exception5entry:  isr_excentry_nocode 5
archi586_isr_exception6entry:  isr_excentry_nocode 6
/* archi586_isr_exception7entry:  isr_excentry_nocode 7 */
archi586_isr_exception7entry:  jmp archi586_isr_exception7entry
archi586_isr_exception8entry:  isr_excentry        8
archi586_isr_exception9entry:  isr_excentry_nocode 9
archi586_isr_exception10entry: isr_excentry        10
archi586_isr_exception11entry: isr_excentry        11
archi586_isr_exception12entry: isr_excentry        12
archi586_isr_exception13entry: isr_excentry        13
archi586_isr_exception14entry: isr_excentry        14
archi586_isr_exception15entry: isr_excentry_nocode 15
archi586_isr_exception16entry: isr_excentry_nocode 16
archi586_isr_exception17entry: isr_excentry        17
archi586_isr_exception18entry: isr_excentry_nocode 18
archi586_isr_exception19entry: isr_excentry_nocode 19
archi586_isr_exception20entry: isr_excentry_nocode 20
archi586_isr_exception21entry: isr_excentry        21
archi586_isr_exception22entry: isr_excentry_nocode 22
archi586_isr_exception23entry: isr_excentry_nocode 23
archi586_isr_exception24entry: isr_excentry_nocode 24
archi586_isr_exception25entry: isr_excentry_nocode 25
archi586_isr_exception26entry: isr_excentry_nocode 26
archi586_isr_exception27entry: isr_excentry_nocode 27
archi586_isr_exception28entry: isr_excentry_nocode 28
archi586_isr_exception29entry: isr_excentry        29
archi586_isr_exception30entry: isr_excentry        30
archi586_isr_exception31entry: isr_excentry_nocode 31

archi586_isr_interrupt32entry:  isr_intentry 32
archi586_isr_interrupt33entry:  isr_intentry 33
archi586_isr_interrupt34entry:  isr_intentry 34
archi586_isr_interrupt35entry:  isr_intentry 35
archi586_isr_interrupt36entry:  isr_intentry 36
archi586_isr_interrupt37entry:  isr_intentry 37
archi586_isr_interrupt38entry:  isr_intentry 38
archi586_isr_interrupt39entry:  isr_intentry 39
archi586_isr_interrupt40entry:  isr_intentry 40
archi586_isr_interrupt41entry:  isr_intentry 41
archi586_isr_interrupt42entry:  isr_intentry 42
archi586_isr_interrupt43entry:  isr_intentry 43
archi586_isr_interrupt44entry:  isr_intentry 44
archi586_isr_interrupt45entry:  isr_intentry 45
archi586_isr_interrupt46entry:  isr_intentry 46
archi586_isr_interrupt47entry:  isr_intentry 47
archi586_isr_interrupt48entry:  isr_intentry 48
archi586_isr_interrupt49entry:  isr_intentry 49
archi586_isr_interrupt50entry:  isr_intentry 50
archi586_isr_interrupt51entry:  isr_intentry 51
archi586_isr_interrupt52entry:  isr_intentry 52
archi586_isr_interrupt53entry:  isr_intentry 53
archi586_isr_interrupt54entry:  isr_intentry 54
archi586_isr_interrupt55entry:  isr_intentry 55
archi586_isr_interrupt56entry:  isr_intentry 56
archi586_isr_interrupt57entry:  isr_intentry 57
archi586_isr_interrupt58entry:  isr_intentry 58
archi586_isr_interrupt59entry:  isr_intentry 59
archi586_isr_interrupt60entry:  isr_intentry 60
archi586_isr_interrupt61entry:  isr_intentry 61
archi586_isr_interrupt62entry:  isr_intentry 62
archi586_isr_interrupt63entry:  isr_intentry 63
archi586_isr_interrupt64entry:  isr_intentry 64
archi586_isr_interrupt65entry:  isr_intentry 65
archi586_isr_interrupt66entry:  isr_intentry 66
archi586_isr_interrupt67entry:  isr_intentry 67
archi586_isr_interrupt68entry:  isr_intentry 68
archi586_isr_interrupt69entry:  isr_intentry 69
archi586_isr_interrupt70entry:  isr_intentry 70
archi586_isr_interrupt71entry:  isr_intentry 71
archi586_isr_interrupt72entry:  isr_intentry 72
archi586_isr_interrupt73entry:  isr_intentry 73
archi586_isr_interrupt74entry:  isr_intentry 74
archi586_isr_interrupt75entry:  isr_intentry 75
archi586_isr_interrupt76entry:  isr_intentry 76
archi586_isr_interrupt77entry:  isr_intentry 77
archi586_isr_interrupt78entry:  isr_intentry 78
archi586_isr_interrupt79entry:  isr_intentry 79
archi586_isr_interrupt80entry:  isr_intentry 80
archi586_isr_interrupt81entry:  isr_intentry 81
archi586_isr_interrupt82entry:  isr_intentry 82
archi586_isr_interrupt83entry:  isr_intentry 83
archi586_isr_interrupt84entry:  isr_intentry 84
archi586_isr_interrupt85entry:  isr_intentry 85
archi586_isr_interrupt86entry:  isr_intentry 86
archi586_isr_interrupt87entry:  isr_intentry 87
archi586_isr_interrupt88entry:  isr_intentry 88
archi586_isr_interrupt89entry:  isr_intentry 89
archi586_isr_interrupt90entry:  isr_intentry 90
archi586_isr_interrupt91entry:  isr_intentry 91
archi586_isr_interrupt92entry:  isr_intentry 92
archi586_isr_interrupt93entry:  isr_intentry 93
archi586_isr_interrupt94entry:  isr_intentry 94
archi586_isr_interrupt95entry:  isr_intentry 95
archi586_isr_interrupt96entry:  isr_intentry 96
archi586_isr_interrupt97entry:  isr_intentry 97
archi586_isr_interrupt98entry:  isr_intentry 98
archi586_isr_interrupt99entry:  isr_intentry 99
archi586_isr_interrupt100entry: isr_intentry 100
archi586_isr_interrupt101entry: isr_intentry 101
archi586_isr_interrupt102entry: isr_intentry 102
archi586_isr_interrupt103entry: isr_intentry 103
archi586_isr_interrupt104entry: isr_intentry 104
archi586_isr_interrupt105entry: isr_intentry 105
archi586_isr_interrupt106entry: isr_intentry 106
archi586_isr_interrupt107entry: isr_intentry 107
archi586_isr_interrupt108entry: isr_intentry 108
archi586_isr_interrupt109entry: isr_intentry 109
archi586_isr_interrupt110entry: isr_intentry 110
archi586_isr_interrupt111entry: isr_intentry 111
archi586_isr_interrupt112entry: isr_intentry 112
archi586_isr_interrupt113entry: isr_intentry 113
archi586_isr_interrupt114entry: isr_intentry 114
archi586_isr_interrupt115entry: isr_intentry 115
archi586_isr_interrupt116entry: isr_intentry 116
archi586_isr_interrupt117entry: isr_intentry 117
archi586_isr_interrupt118entry: isr_intentry 118
archi586_isr_interrupt119entry: isr_intentry 119
archi586_isr_interrupt120entry: isr_intentry 120
archi586_isr_interrupt121entry: isr_intentry 121
archi586_isr_interrupt122entry: isr_intentry 122
archi586_isr_interrupt123entry: isr_intentry 123
archi586_isr_interrupt124entry: isr_intentry 124
archi586_isr_interrupt125entry: isr_intentry 125
archi586_isr_interrupt126entry: isr_intentry 126
archi586_isr_interrupt127entry: isr_intentry 127
archi586_isr_interrupt128entry: isr_intentry 128
archi586_isr_interrupt129entry: isr_intentry 129
archi586_isr_interrupt130entry: isr_intentry 130
archi586_isr_interrupt131entry: isr_intentry 131
archi586_isr_interrupt132entry: isr_intentry 132
archi586_isr_interrupt133entry: isr_intentry 133
archi586_isr_interrupt134entry: isr_intentry 134
archi586_isr_interrupt135entry: isr_intentry 135
archi586_isr_interrupt136entry: isr_intentry 136
archi586_isr_interrupt137entry: isr_intentry 137
archi586_isr_interrupt138entry: isr_intentry 138
archi586_isr_interrupt139entry: isr_intentry 139
archi586_isr_interrupt140entry: isr_intentry 140
archi586_isr_interrupt141entry: isr_intentry 141
archi586_isr_interrupt142entry: isr_intentry 142
archi586_isr_interrupt143entry: isr_intentry 143
archi586_isr_interrupt144entry: isr_intentry 144
archi586_isr_interrupt145entry: isr_intentry 145
archi586_isr_interrupt146entry: isr_intentry 146
archi586_isr_interrupt147entry: isr_intentry 147
archi586_isr_interrupt148entry: isr_intentry 148
archi586_isr_interrupt149entry: isr_intentry 149
archi586_isr_interrupt150entry: isr_intentry 150
archi586_isr_interrupt151entry: isr_intentry 151
archi586_isr_interrupt152entry: isr_intentry 152
archi586_isr_interrupt153entry: isr_intentry 153
archi586_isr_interrupt154entry: isr_intentry 154
archi586_isr_interrupt155entry: isr_intentry 155
archi586_isr_interrupt156entry: isr_intentry 156
archi586_isr_interrupt157entry: isr_intentry 157
archi586_isr_interrupt158entry: isr_intentry 158
archi586_isr_interrupt159entry: isr_intentry 159
archi586_isr_interrupt160entry: isr_intentry 160
archi586_isr_interrupt161entry: isr_intentry 161
archi586_isr_interrupt162entry: isr_intentry 162
archi586_isr_interrupt163entry: isr_intentry 163
archi586_isr_interrupt164entry: isr_intentry 164
archi586_isr_interrupt165entry: isr_intentry 165
archi586_isr_interrupt166entry: isr_intentry 166
archi586_isr_interrupt167entry: isr_intentry 167
archi586_isr_interrupt168entry: isr_intentry 168
archi586_isr_interrupt169entry: isr_intentry 169
archi586_isr_interrupt170entry: isr_intentry 170
archi586_isr_interrupt171entry: isr_intentry 171
archi586_isr_interrupt172entry: isr_intentry 172
archi586_isr_interrupt173entry: isr_intentry 173
archi586_isr_interrupt174entry: isr_intentry 174
archi586_isr_interrupt175entry: isr_intentry 175
archi586_isr_interrupt176entry: isr_intentry 176
archi586_isr_interrupt177entry: isr_intentry 177
archi586_isr_interrupt178entry: isr_intentry 178
archi586_isr_interrupt179entry: isr_intentry 179
archi586_isr_interrupt180entry: isr_intentry 180
archi586_isr_interrupt181entry: isr_intentry 181
archi586_isr_interrupt182entry: isr_intentry 182
archi586_isr_interrupt183entry: isr_intentry 183
archi586_isr_interrupt184entry: isr_intentry 184
archi586_isr_interrupt185entry: isr_intentry 185
archi586_isr_interrupt186entry: isr_intentry 186
archi586_isr_interrupt187entry: isr_intentry 187
archi586_isr_interrupt188entry: isr_intentry 188
archi586_isr_interrupt189entry: isr_intentry 189
archi586_isr_interrupt190entry: isr_intentry 190
archi586_isr_interrupt191entry: isr_intentry 191
archi586_isr_interrupt192entry: isr_intentry 192
archi586_isr_interrupt193entry: isr_intentry 193
archi586_isr_interrupt194entry: isr_intentry 194
archi586_isr_interrupt195entry: isr_intentry 195
archi586_isr_interrupt196entry: isr_intentry 196
archi586_isr_interrupt197entry: isr_intentry 197
archi586_isr_interrupt198entry: isr_intentry 198
archi586_isr_interrupt199entry: isr_intentry 199
archi586_isr_interrupt200entry: isr_intentry 200
archi586_isr_interrupt201entry: isr_intentry 201
archi586_isr_interrupt202entry: isr_intentry 202
archi586_isr_interrupt203entry: isr_intentry 203
archi586_isr_interrupt204entry: isr_intentry 204
archi586_isr_interrupt205entry: isr_intentry 205
archi586_isr_interrupt206entry: isr_intentry 206
archi586_isr_interrupt207entry: isr_intentry 207
archi586_isr_interrupt208entry: isr_intentry 208
archi586_isr_interrupt209entry: isr_intentry 209
archi586_isr_interrupt210entry: isr_intentry 210
archi586_isr_interrupt211entry: isr_intentry 211
archi586_isr_interrupt212entry: isr_intentry 212
archi586_isr_interrupt213entry: isr_intentry 213
archi586_isr_interrupt214entry: isr_intentry 214
archi586_isr_interrupt215entry: isr_intentry 215
archi586_isr_interrupt216entry: isr_intentry 216
archi586_isr_interrupt217entry: isr_intentry 217
archi586_isr_interrupt218entry: isr_intentry 218
archi586_isr_interrupt219entry: isr_intentry 219
archi586_isr_interrupt220entry: isr_intentry 220
archi586_isr_interrupt221entry: isr_intentry 221
archi586_isr_interrupt222entry: isr_intentry 222
archi586_isr_interrupt223entry: isr_intentry 223
archi586_isr_interrupt224entry: isr_intentry 224
archi586_isr_interrupt225entry: isr_intentry 225
archi586_isr_interrupt226entry: isr_intentry 226
archi586_isr_interrupt227entry: isr_intentry 227
archi586_isr_interrupt228entry: isr_intentry 228
archi586_isr_interrupt229entry: isr_intentry 229
archi586_isr_interrupt230entry: isr_intentry 230
archi586_isr_interrupt231entry: isr_intentry 231
archi586_isr_interrupt232entry: isr_intentry 232
archi586_isr_interrupt233entry: isr_intentry 233
archi586_isr_interrupt234entry: isr_intentry 234
archi586_isr_interrupt235entry: isr_intentry 235
archi586_isr_interrupt236entry: isr_intentry 236
archi586_isr_interrupt237entry: isr_intentry 237
archi586_isr_interrupt238entry: isr_intentry 238
archi586_isr_interrupt239entry: isr_intentry 239
archi586_isr_interrupt240entry: isr_intentry 240
archi586_isr_interrupt241entry: isr_intentry 241
archi586_isr_interrupt242entry: isr_intentry 242
archi586_isr_interrupt243entry: isr_intentry 243
archi586_isr_interrupt244entry: isr_intentry 244
archi586_isr_interrupt245entry: isr_intentry 245
archi586_isr_interrupt246entry: isr_intentry 246
archi586_isr_interrupt247entry: isr_intentry 247
archi586_isr_interrupt248entry: isr_intentry 248
archi586_isr_interrupt249entry: isr_intentry 249
archi586_isr_interrupt250entry: isr_intentry 250
archi586_isr_interrupt251entry: isr_intentry 251
archi586_isr_interrupt252entry: isr_intentry 252
archi586_isr_interrupt253entry: isr_intentry 253
archi586_isr_interrupt254entry: isr_intentry 254
archi586_isr_interrupt255entry: isr_intentry 255
