#!/bin/sh
RELEASE=$(date +%y.%m.%d)
VERSION=$(git describe --tags --dirty --always)
echo "// Generated by genversionfile.sh ($(date))"
echo "#pragma once"
echo ""
echo "#define YJKOS_RELEASE \"$RELEASE\""
echo "#define YJKOS_VERSION \"$VERSION\""
echo ""